name: Publish binaries
on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish for wasm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: npm/bin/circom.wasm
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          asset_name: circom.wasm
